version: '3'
x-spark-common: &spark-common
  # image: bitnami/spark:3.5.6
  build:
    context: .
    dockerfile: spark.Dockerfile
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./jars:/opt/bitnami/spark/jars
    - ./scripts:/opt/bitnami/spark/scripts
  networks:
    - code-with-yu

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    env_file:
      - .env
    user: root

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    env_file:
      - .env
  
networks:
  code-with-yu: